#!/bin/sh

chmod +x /usr/sbin/smartdns
chmod +x /etc/init.d/smartdns

[ "${IPKG_NO_SCRIPT}" = "1" ] && exit 0
. ${IPKG_INSTROOT}/lib/functions.sh
default_postinst $0 $@
ret=$?
/etc/init.d/smartdns enable
exit $ret

